export { default as logo} from '../../assets/admin/assets/img/logo.png';
export { default as logoWhite} from '../../assets/admin/assets/img/logo-white.png';
export { default as logoSmall} from '../../assets/admin/assets/img/logo-small.png';
export { default as favicon} from '../../assets/admin/assets/img/favicon.png';
export { default as avatar01} from '../../assets/admin/assets/img/profiles/avatar-01.jpg';
export { default as avatar07} from '../../assets/admin/assets/img/profiles/avatar-07.jpg';
export { default as avatar08} from '../../assets/admin/assets/img/profiles/avatar-08.jpg';
export { default as avatar09} from '../../assets/admin/assets/img/profiles/avatar-09.jpg';
export { default as avatar05} from '../../assets/admin/assets/img/profiles/avatar-05.jpg';
export { default as avatar04} from '../../assets/admin/assets/img/profiles/avatar-04.jpg';
export { default as avatar02} from '../../assets/admin/assets/img/profiles/avatar-02.jpg';
export { default as avatar03} from '../../assets/admin/assets/img/profiles/avatar-03.jpg';
export { default as avatar13} from '../../assets/admin/assets/img/profiles/avatar-13.jpg';
export { default as avatar12} from '../../assets/admin/assets/img/profiles/avatar-12.jpg';
export { default as avatar11} from '../../assets/admin/assets/img/profiles/avatar-11.jpg';
export { default as avatar06} from '../../assets/admin/assets/img/profiles/avatar-06.jpg';
export { default as avatar10} from '../../assets/admin/assets/img/profiles/avatar-10.jpg';
export { default as img01} from '../../assets/admin/assets/img/img-01.jpg'
export { default as patient} from '../../assets/admin/assets/img/patients/patient.jpg'
export { default as patient1} from '../../assets/admin/assets/img/patients/patient1.jpg'
export { default as patient2} from '../../assets/admin/assets/img/patients/patient2.jpg'
export { default as patient3} from '../../assets/admin/assets/img/patients/patient3.jpg'
export { default as patient4} from '../../assets/admin/assets/img/patients/patient4.jpg'
export { default as patient5} from '../../assets/admin/assets/img/patients/patient5.jpg'
export { default as patient6} from '../../assets/admin/assets/img/patients/patient6.jpg'
export { default as patient7} from '../../assets/admin/assets/img/patients/patient7.jpg'
export { default as patient8} from '../../assets/admin/assets/img/patients/patient8.jpg'
export { default as patient9} from '../../assets/admin/assets/img/patients/patient9.jpg'
export { default as patient10} from '../../assets/admin/assets/img/patients/patient10.jpg'
export { default as patient11} from '../../assets/admin/assets/img/patients/patient11.jpg'
export { default as patient12} from '../../assets/admin/assets/img/patients/patient12.jpg'
export { default as patient13} from '../../assets/admin/assets/img/patients/patient13.jpg'
export { default as patient14} from '../../assets/admin/assets/img/patients/patient14.jpg'
export { default as patient15} from '../../assets/admin/assets/img/patients/patient15.jpg'
export { default as doctor_thumb_01} from '../../assets/admin/assets/img/doctors/doctor-thumb-01.jpg'
export { default as doctor_thumb_02} from '../../assets/admin/assets/img/doctors/doctor-thumb-02.jpg'
export { default as doctor_thumb_03} from '../../assets/admin/assets/img/doctors/doctor-thumb-03.jpg'
export { default as doctor_thumb_04} from '../../assets/admin/assets/img/doctors/doctor-thumb-04.jpg'
export { default as doctor_thumb_05} from '../../assets/admin/assets/img/doctors/doctor-thumb-05.jpg'
export { default as doctor_thumb_06} from '../../assets/admin/assets/img/doctors/doctor-thumb-06.jpg'
export { default as doctor_thumb_07} from '../../assets/admin/assets/img/doctors/doctor-thumb-07.jpg'
export { default as doctor_thumb_08} from '../../assets/admin/assets/img/doctors/doctor-thumb-08.jpg'
export { default as doctor_thumb_09} from '../../assets/admin/assets/img/doctors/doctor-thumb-09.jpg'
export { default as doctor_thumb_10} from '../../assets/admin/assets/img/doctors/doctor-thumb-10.jpg'
export { default as doctor_thumb_11} from '../../assets/admin/assets/img/doctors/doctor-thumb-11.jpg'
export { default as doctor_thumb_12} from '../../assets/admin/assets/img/doctors/doctor-thumb-12.jpg'
export { default as specialities_01} from '../../assets/admin/assets/img/specialities/specialities-01.png'
export { default as specialities_02} from '../../assets/admin/assets/img/specialities/specialities-02.png'
export { default as specialities_03} from '../../assets/admin/assets/img/specialities/specialities-03.png'
export { default as specialities_04} from '../../assets/admin/assets/img/specialities/specialities-04.png'
export { default as specialities_05} from '../../assets/admin/assets/img/specialities/specialities-05.png'
export { default as doctor_01} from '../../assets/admin/assets/img/doctors/doctor-01.jpg'
export { default as doctor_02} from '../../assets/admin/assets/img/doctors/doctor-02.jpg'
export { default as doctor_03} from '../../assets/admin/assets/img/doctors/doctor-03.jpg'
export { default as doctor_04} from '../../assets/admin/assets/img/doctors/doctor-04.jpg'
export { default as doctor_05} from '../../assets/admin/assets/img/doctors/doctor-05.jpg'
export { default as doctor_06} from '../../assets/admin/assets/img/doctors/doctor-06.jpg'
export { default as doctor_07} from '../../assets/admin/assets/img/doctors/doctor-07.jpg'
export { default as doctor_08} from '../../assets/admin/assets/img/doctors/doctor-08.jpg'
export { default as doctor_09} from '../../assets/admin/assets/img/doctors/doctor-09.jpg'
export { default as doctor_10} from '../../assets/admin/assets/img/doctors/doctor-10.jpg'
export { default as doctor_11} from '../../assets/admin/assets/img/doctors/doctor-11.jpg'
export { default as doctor_12} from '../../assets/admin/assets/img/doctors/doctor-12.jpg'






