export { default as IMG01} from '../../../../../assets/img/doctor-01.jpg';
export { default as IMG02} from '../../../../../assets/img/doctor-02.jpg';
export { default as IMG03} from '../../../../../assets/img/doctor-03.jpg';
export { default as IMG04} from '../../../../../assets/img/doctor-04.jpg';
export { default as IMG05} from '../../../../../assets/img/doctor-05.jpg';
export { default as IMG06} from '../../../../../assets/img/doctor-06.jpg';
export { default as IMG07} from '../../../../../assets/img/doctor-07.jpg';
export { default as IMG08} from '../../../../../assets/img/doctor-08.jpg';
export { default as IMG09} from '../../../../../assets/img/doctor-09.jpg';